<template>
  <div>
    <div class="desc">
      <p>All of the images on this site are created by a computer, generated by an algorithm known as an “adversarial network”. In short, this algorithm learns how to turn random noise into images by playing a game against itself. One module generates samples, while the other distinguishes the samples from real fine art. Each learns to best the other and, if the balance is right, they will eventually converge to a stable state.</p>
      <p>Please enjoy your time in this “probability space” formed from thousands of years of human creative achievement.</p>
    </div>
    <div class="spinner" v-if="loading"></div>
    <div class="loading-message" v-if="loading">Generating Images...</div>
    <div class="error" v-if="error">{{ error }}</div>
    <div class="images">
      <div v-for="url in images">
        <img :src="url"></img>
      </div>
    </div>
  </div>
</template>

<script>
import request from 'superagent';
import Vue from 'vue';

export default {
  data () {
    return {
      loading: true,
      error: null,
      images: []
    }
  },
  beforeMount () {
    request
      .post('http://35.164.145.72:9090/images/')
      .send({ size: "16" })
      .end((err, res) => {
        if (err) {
          this.error = err.message;
        } else {
          this.images = res.body
        }
        this.loading = false;
      });
  }
};

</script>

<style>
.desc {
  text-align: left;
  font-size: 1.3rem;
  margin-bottom: 30px;
  line-height: 2rem;
}
.images div {
  display: inline-block;
  margin: 10px;
}
.error {
  color: #DD0000;
}
.loading-message {
  text-transform: uppercase;
  letter-spacing: 2px;
  margin-top: 15px;
}
.spinner {
  margin: 40px auto 0 auto;
  height: 60px;
  width: 60px;
  position: relative;
  -webkit-animation: rotation .6s infinite linear;
  -moz-animation: rotation .6s infinite linear;
  -o-animation: rotation .6s infinite linear;
  animation: rotation .6s infinite linear;
  border-left: 6px solid rgba(29, 242, 242, .15);
  border-right: 6px solid rgba(29, 242, 242, .15);
  border-bottom: 6px solid rgba(29, 242, 242, .15);
  border-top: 6px solid rgba(29, 242, 242, .8);
  border-radius: 100%;
}

@-webkit-keyframes rotation {
  from {
    -webkit-transform: rotate(0deg);
  }
  to {
    -webkit-transform: rotate(359deg);
  }
}

@-moz-keyframes rotation {
  from {
    -moz-transform: rotate(0deg);
  }
  to {
    -moz-transform: rotate(359deg);
  }
}

@-o-keyframes rotation {
  from {
    -o-transform: rotate(0deg);
  }
  to {
    -o-transform: rotate(359deg);
  }
}

@keyframes rotation {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(359deg);
  }
}
</style>
